name: Build and push Docker image
on:
  push:
    branches:
      - main
    tags:
      - '1.*'
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build image
        run: |
          docker build . -t raksmeyjr/student:latest
          docker build . -t raksmeyjr/student:1.0

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: raksmeyjr/student:1.0
          severity: CRITICAL
          format: table
          output: console
          fail-on-severity: CRITICAL

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOEKN }}

      - name: Push image to Docker Hub
        run: |
          echo "Push image to Docker Hub..."
          docker push raksmeyjr/student:latest
          docker push raksmeyjr/student:1.0